baseURL: https://aybe.org/
title: Ayrat Belyaev
theme: PaperMod
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
googleAnalytics: G-MFD8PM59LW

defaultContentLanguage: ru
languages:
    ru:
        languageName: ðŸ‡·ðŸ‡º
        contentDir: content
        menu:
          main:
            - name: Ð¿Ð¾Ð¸ÑÐº
              url: /search
              weight: 1
            - name: Ð°Ñ€Ñ…Ð¸Ð²
              url: /archives
              weight: 2
            - name: Ñ‚ÐµÐ³Ð¸
              url: /tags
              weight: 3
        params:
          comments: true
          description: ÐŸÐµÑ€ÑÐ¾Ð½Ð°Ð»ÑŒÐ½Ñ‹Ð¹ Ð±Ð»Ð¾Ð³ ÐÐ¹Ñ€Ð°Ñ‚Ð° Ð‘ÐµÐ»ÑÐµÐ²Ð°
          keywords:
            - ayrat
            - belyaev
            - Ð°Ð¹Ñ€Ð°Ñ‚
            - Ð±ÐµÐ»ÑÐµÐ²
            - blog
            - Ð±Ð»Ð¾Ð³
            - xbreaker
          homeInfoParams:
            title: ÐŸÑ€Ð¸Ð²ÐµÑ‚ ðŸ‘‹
            Content: >
              ÐŸÐ¾Ð·Ð¶Ðµ Ð·Ð´ÐµÑÑŒ Ð±ÑƒÐ´ÐµÑ‚ Ð½Ð°Ð¿Ð¸ÑÐ°Ð½Ð¾ Ñ‡Ñ‚Ð¾-Ñ‚Ð¾ Ð·Ð°Ð½Ð¸Ð¼Ð°Ñ‚ÐµÐ»ÑŒÐ½Ð¾Ðµ
        weight: 1

taxonomies:
    category: categories
    tag: tags
    series: series

permalinks:
  posts: /:year/:month/:slug/

minify:
  disableJSON: true
  disableXML: true
  minifyOutput: true

params:
  env: production
  author: Ayrat Belyaev
  emailhash: 8ba9fb6714b8b017f86e5fcb2752c7a0
  description: Personal space
  keywords:
    - blog
    - ayrat
    - belyaev
    - progamming

  staticman:
    api: https://aybeorg.onrender.com/v2/entry/xbreaker/xbreaker.github.io/main/comments
    recaptcha:
      enabled: true
      siteKey: "6LfuipkbAAAAAFmcmiZa7HYmEk40r0JJ-ua665vQ"
      secret: "w0e8kjpH56nyKZkvYX0Oe4kOTSOxu3c1rr2Cw4L67iB0Gx1MTBSemXn0pY+05X3Lezu/FEORlYMB15Mr9lZHSDhdpkee2l3dw3SMD7BAkJpAErtXqyC5PsSinCsZf0989VObxa/74QAp+NyF7Zr4lbY+equDeBPN9p/TqwSv0jn5Wdj2xJOoCfdThiAEeN+6DRXIqnnIMWZ6PPVkiYuBQb8zYvywNgaJ18ctucTKlnOI3SsVR8G4R86jtkvn/+cl9u+2Tu61yS1HPwz78/Aips9OdRFcLdsConD6QqbJV4R0lKFArqjD7smPKal3z/WqH1P4gED54NuNSI6VQt+Tu0J25qgEmZuL+3tJp+Jr1WyGCjrHdvatxa/dTDQgV2F+XLSLd/RmC9GbT3ukEB1CI/IFvznuj4iHtBNog7v7mwht4CVUGzIsaHNSkzMdjP/Tbt8K7YptjkhyUISuamDwbauXiTUlQishzwP8l3iM0CJRh3gKQGBP9u5svoctjCgzQzjgHfqHDgnKD2oyzSl4l4/UmwetxCEkvmY9h05VinAqMKu+wg1TTpKh0xJ0LW7TGoctfoupnzM+XTUy0UGxHBNdVFDVoP9xoQcZgkfw2yWm96t3K78kRMqWbiNqw0ZuJPy6x1IFeuPLh9CLhwflfkJW1j8UbG+WHzQLgJJUIkQ="

  defaultTheme: auto
  comments: true

  homeInfoParams:
    Title: Hello! ðŸ‘‹
    Content: >
      Welcome to my home page
  socialIcons:
    - name: email
      url: mailto:me@aybe.org
    - name: github
      url: https://github.com/xbreaker
    - name: twitter
      url: https://twitter.com/xbreaker
    - name: instagram
      url: https://instagram.com/xb_r
    - name: telegram
      url: https://t.me/xbreaker
    - name: linkedin
      url: https://www.linkedin.com/in/xbreaker
    - name: rss
      url: https://aybe.org/index.xml

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  disableCodeCopy: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  displayFullLangName: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: /favicon.ico
    favicon16x16: /favicon-16x16.png
    favicon32x32: favicon-32x32.png
    apple_touch_icon: /apple-touch-icon.png
    safari_pinned_tab: /favicon-32x32.png

  label:
    text: Ayrat Belyaev
    icon: /img/avatar-35.jpg
    iconHeight: 35

outputs:
  home:
    - HTML
    - RSS
    - JSON
